### ISSUE TITLE
Conda cerate env error with requirements-dev.txt

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#100]
I've tried to create a conda env using requirements-dev.txt, to install fludashboard-dev, and got an error at the shell requirement:
```
marfcg@marfcg-Satellite-L840:~/codes/FluVigilanciaBR/fludashboard$ conda env create -f requirements-dev.txt -n fludashboard-dev
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/marfcg/miniconda3  (writable)
    default environment : /home/marfcg/miniconda3
       envs directories : /home/marfcg/miniconda3/envs
                          /home/marfcg/.conda/envs
          package cache : /home/marfcg/miniconda3/pkgs
                          /home/marfcg/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/marfcg/.condarc
             netrc file : /home/marfcg/.netrc
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-97-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/marfcg/miniconda3/bin/conda-env create -f requirements-dev.txt -n fludashboard-dev`




    Traceback (most recent call last):
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 75, in load
        return loader.get_single_data()
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 56, in get_single_node
        if not self.check_event(StreamEndEvent):
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 116, in check_event
        self.current_event = self.state()
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 194, in parse_document_start
        self.peek_token().start_mark)
    ruamel_yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
      in "<unicode string>", line 7, column 1:
        sh
        ^
```
Setting up an env with requirements.txt went ok, though.

**Comment by marfcg** [comment]
Ok. I see what the problem is. I assumed it was the same file as conda uses for setting up the environment, which it is not. My bad.

**Comment by xmnlab** [comment]
ok .. another way to create a env is:

```sh

conda create -y python=3.6 -n fludashboard --file requirements.txt

```
