### ISSUE TITLE
Data for years < 2017 not shown

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#125]
This has showed up as a result of #120 fix.
Relevant info:

The issue, then, is that when a year without historical estimations is selected (anything prior to 2017), the data is not shown. This might be related to issue #119.
I believe the system is build in a way where historical_estimated_values is the main data source, while it should be the current_estimated_values one. While the former has the data at time of previous estimates ran, the later is the one with the most up-to-date notification data for all epiweeks.

Relevant traceback when selecting previous years:
```
Traceback (most recent call last):
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/storage/Marcelo/codes/FluVigilanciaBR/fludashboard/fludashboard/libs/views.py", line 127, in get_data
    return apply_filter_alert_by_epiweek(df).to_json(orient='records')
  File "/storage/Marcelo/codes/FluVigilanciaBR/fludashboard/fludashboard/libs/calc_flu_alert.py", line 63, in apply_filter_alert_by_epiweek
    df_alert = df_alert.assign(alert=alert_col)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/pandas/core/frame.py", line 2694, in assign
    data[k] = v
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/pandas/core/frame.py", line 2519, in __setitem__
    self._set_item(key, value)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/pandas/core/frame.py", line 2584, in _set_item
    self._ensure_valid_index(value)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/pandas/core/frame.py", line 2566, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
```

**Comment by marfcg** [comment]
The column year from mem_typical table is a reference for the year in which it was produced. The typical curves are the same for all epiyears, since the are a reference for expected seasonal trend.
Therefore, when generating the view, we don't have to check whether mem_typical.year = (selected year).
